spring:
  data:
    mongodb:
      host: auth-mongodb
      username: ${MONGODB_APPLICATION_USER}
      password: ${MONGODB_APPLICATION_PASS}
      database: ${MONGODB_APPLICATION_DATABASE}
      port: 27017
server:
  port: 8083
  contextPath: /uaa